
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "demo.h"

void Demo__ctx_type_3_init(Demo__ctx_type_3 &_output_){
   Demo__ctx_type_3 _ctx;
   _ctx.rate = 0x0 /* 0.000000 */;
   _ctx.phase = 0x0 /* 0.000000 */;
   Demo__ctx_type_1_init(_ctx._inst1f1);
   _output_ = _ctx;
   return ;
}

fix16_t Demo_phasor(Demo__ctx_type_3 &_ctx, fix16_t pitch, uint8_t reset){
   if(Demo_change(_ctx._inst1f1,pitch)){
      _ctx.rate = Demo_pitchToRate(pitch);
   }
   if(reset){
      _ctx.phase = 0x0 /* 0.000000 */;
   }
   else
   {
      _ctx.phase = (_ctx.phase + _ctx.rate);
   }
   if(_ctx.phase > 0x10000 /* 1.000000 */){
      _ctx.phase = (-0x10000 /* -1.000000 */ + _ctx.phase);
   }
   return _ctx.phase;
}

void Demo__ctx_type_4_init(Demo__ctx_type_4 &_output_){
   Demo__ctx_type_4 _ctx;
   _ctx.volume = 0x0 /* 0.000000 */;
   _ctx.pre_phase1 = 0x0 /* 0.000000 */;
   _ctx.pitch = 0x0 /* 0.000000 */;
   _ctx.detune = 0x0 /* 0.000000 */;
   Demo__ctx_type_0_init(_ctx._inst4c7);
   Demo__ctx_type_3_init(_ctx._inst327);
   Demo__ctx_type_0_init(_ctx._inst2c7);
   Demo__ctx_type_3_init(_ctx._inst127);
   _output_ = _ctx;
   return ;
}

fix16_t Demo_process(Demo__ctx_type_4 &_ctx, fix16_t input){
   fix16_t phase1;
   phase1 = Demo_phasor(_ctx._inst127,_ctx.pitch,false);
   fix16_t comp;
   comp = (0x10000 /* 1.000000 */ + (- phase1));
   uint8_t reset;
   reset = ((_ctx.pre_phase1 + (- phase1)) > 0x8000 /* 0.500000 */);
   _ctx.pre_phase1 = phase1;
   fix16_t phase2;
   phase2 = Demo_phasor(_ctx._inst327,(_ctx.pitch + (Demo_smooth(_ctx._inst2c7,_ctx.detune) << 5)),reset);
   fix16_t sine;
   sine = fix_sin(fix_mul(0x6487e /* 6.283185 */,phase2));
   return fix_mul(fix_mul(comp,sine),Demo_smooth(_ctx._inst4c7,_ctx.volume));
}


